### PR TITLE
Add support for http4s 0.20.0-M3

### PR DESCRIPTION
**Pull request by randbw**
Copied closely the structure of the `scalapact-http4s-0-18` project with the main difference being I separated `PactStubber` from `PactStubService.scala` and called the class `PactServer` to match the interface it implements.

### CODE REVIEW

**Comment by davesmith00000** [comment]
I appreciate the work, I'm slightly hesitate about bringing it in yet. Do we know when the stable release of version 20 is due out?

I tend not to release against milestone versions because they're unstable and API's change. I also dropped talking about minor versions in the package / folder structures so that we could transparently upgrade.

That's not a no, but at the very least we'd need to drop all reference to M3.

**Comment by randbw** [comment]
I do not know when the stable version 0.20.0 is expected to be released. This was done for work so thought we'd submit the PR :smiley: 

Understand your thinking on milestone version releases. I will update the PR and drop the minor version reference anyway

**Comment by davesmith00000** [comment]
Hello! Sorry for going quiet - end of year busyness.
1. I noticed that you messed with the SNAPSHOT version - can you check it stays aligned with master - I'll bump that when needed.
2. I also noticed that 0.20.0-M4 is out - quick upgrade?

Otherwise if you're happy that it works I think we should get it merged - we don't need to release it - it can just be ready for the official release version. Would be a shame for the work to fall behind the rest of the codebase.

Thanks again, let me know when you're happy.

**Comment by davesmith00000** [comment]
Actually - I'll sort that out, let's just try and get it merged - many thanks for the contribution. :-)

**Comment by randbw** [comment]
My pleasure!

**Pull request merged**
