### PR TITLE
Create additional settingKey to define pattern matching state providers

### PR DESCRIPTION
**Pull request by jtsmith0107**
@davesmith00000 

Resolving the two SettingKey's together got a bit hairy. 

So this approaches rips out the internals and replaces with (String => Boolean), and then maps existing providerStates key into that type. Hope you don't think it's too invasive. 

Going to want tests around the states to make sure default cases are handled well, and that the keys are still allowed individually.

### CODE REVIEW

**Comment by davesmith00000** [comment]
@jtsmith0107 

Thanks for doing this. It's not quite what I was expecting, which isn't a problem, but I'm going to checkout your version and take another look a bit later today so I can digest it more easily. There are a couple of minor things that appear off, but they may well be fine. I'll get back to you shortly.

**Comment by davesmith00000** [comment]
Sorry for the delay on this, I have finally cloned it so I can have a snoop around. First thing to note is that I don't think your repo is up to date. Let me finish reviewing your changes but assuming they're all good you might need to update your fork first.

**Comment by davesmith00000** [comment]
Another slight wrinkle is, how might you see this implementation playing with:
https://github.com/ITV/scala-pact/issues/27

In a nutshell we may need to be able to create two functions to run (set up and tear down) instead of one. I'm not saying the existing implementation would support that elegantly either btw, I'm just throwing you a design question to see what you think:

What would be a nice way to represent setup and tear down of a provider state in the sbt file do you think?

**Comment by davesmith00000** [comment]
```
pact.sbt:23: error: method Resource is not a case class constructor, nor does it have an unapply/unapplySeq method
  case Resource("user", id: String) => // Sample 'Resource:User:id:1234'
       ^
[error] Type error in expression
```

**Comment by jtsmith0107** [comment]
Ok, I've updated and resolved conflicts. I hadn't updated in awhile. I'm not seeing that compile error in my local when under `scalapact-scalatest` and sbt compile, maybe pull this down and try again?

**Comment by jtsmith0107** [comment]
Regarding the setup and teardown, it sounds like it calls for a more complete definition of what must be defined.

Instead of a String => Boolean providerState, we'd probably want a type
```scala
trait ProviderState {
 def setup: => Boolean
 def teardown: => Boolean
}
```
And then we need a mapper that takes "given" string to ProviderState. So the current String => Boolean would become String => ProviderState.

The strongly typed ProviderState's that know their own setup and teardown functions should be enough for the core logic to execute those at the proper time.

**Comment by davesmith00000** [comment]
The error occurs during the verification process. It's funny that it doesn't turn up earlier but perhaps it's because it's a lazily evaluated `.sbt` file that's loaded by reflection or something?

I was thinking something similar for the ProviderState business..

I'll pull down your latest and test it again. :-)

Sorry about the slowness in my responses, I have a lot going on at the moment, please don't be discouraged!

**Comment by davesmith00000** [comment]
I've pulled and the error has gone away. :-)

For future reference if you go to the root of the project in your terminal you can run `bash scripts/local-build-test.sh` for a full rebuild. It's advisable to go an make a coffee while you wait and depending on your laptop spec you might be able to fry an egg on it afterwards but it's pretty thorough.

**Comment by davesmith00000** [comment]
I've updated the docs and added you as a contributor, look out for v 2.1.1 which I hope to release imminently.

**Comment by davesmith00000** [comment]
Oh! Actually it doesn't work (I'll try and fix it).
1) If there is no match, it reports a success
2) Your example code still throws this when the first match case fails:
```
/Users/DaviSmi5/repos/scalapact/scalapact-scalatest/pact.sbt:24: error: method Resource is not a case class constructor, nor does it have an unapply/unapplySeq method
  case Resource("user", id: String) => // Sample 'Resource:User:id:1234'
```
I'll remove this bit and try and fix point 1.

**Comment by davesmith00000** [comment]
Ok, so:

This commit adds a test case to prove the current logic doesn't quite work as expected:
https://github.com/ITV/scala-pact/commit/c1395d60185c8428e84e6db90ccbcd2657cd5a57

To be fair these partial functions were fiddlier than they seem. I re-read your initial implementation and couldn't see anything wrong with it, I only managed to fix it after quite a bit of trial and error and this would not have been possible with the test case.

This commit fixes the issue however:
https://github.com/ITV/scala-pact/commit/ce12dab5c0aeb5344e29a42d6648bfbe379fae95

...and I did another small clean up around the verifier code because it was a bit... rough. Probably still is but it reads better at least.
https://github.com/ITV/scala-pact/commit/ffd6c68e02e24e911f738f4a203a6e41f738dc05

**Comment by davesmith00000** [comment]
Released in version 2.1.1
http://io.itv.com/scala-pact/change-log.html
http://io.itv.com/scala-pact/advanced/provider-states.html

Thanks again :-)

**Comment by davesmith00000** [comment]
We found another problem where you had to supply a providerStateMatcher or it all went to pieces. Easy to miss and hard to test. Fixed (hopefully) in a release just now 2.1.2.

**Pull request merged**
