### PR TITLE
Added possibility to change request per interaction

### PR DESCRIPTION
**Pull request by garraspin**
Hi! 
We are starting to use scala-pact at work but we are missing some functionality offered in other pact libraries. 
This PR is to add the ability to modify the requests of our pacts. We want to mimic the current behaviour of our system, which will add headers to the requests (like authorization)  but they are not really part of the pact. 
I'm looking forwards to hear from your opinion.
Kind regards,
Samuel.

### CODE REVIEW

**Comment by garraspin** [comment]
I implemented your requests (good points). I am stuck with a test though. Maybe you can check why it doesn't want to pass.

**Comment by garraspin** [comment]
@davesmith00000 Is it better now?

**Comment by davesmith00000** [comment]
Hi, Sorry for the delay! I've reviewed the PR and it looks good.

If I'm nitpicking I think I'd rename:
```scala
case class ProviderStateResult(result: Boolean, modifyRequest: InteractionRequest => InteractionRequest)
```
to something like
```scala
case class ProviderStateResult(setupSuccess: Boolean, requestModifier: InteractionRequest => InteractionRequest)
```
...but I can do that later. :-)

**Comment by garraspin** [comment]
Thanks for merging! And indeed those are more meaning names.

**Pull request merged**
