### PR TITLE
Adds support for http basic authentication

### LINKED ISSUE #110: scala-pact does not support HTTP Basic auth?
I've tried to set it up in my pact.sbt like this:
`pactBrokerAddress := "http://username:password@pact-broker.local"`

and whenever i run `sbt pactPublish` everything seems to go okay until the last second (when the actual publishing happens):
```
SimpleResponse(401,Map(Server -> nginx/1.14.0 + Phusion Passenger 5.3.6, Connection -> keep-alive, Content-Length -> 0, WWW-Authenticate -> Basic realm="Restricted area", Content-Type -> text/plain, Date -> Mon, 19 Nov 2018 09:32:28 GMT, X-Powered-By -> Phusion Passenger 5.3.6, Status -> 401 Unauthorized),Some())
Failed: 401, Some()
```

If i replace the header here:
https://github.com/ITV/scala-pact/blob/602aeb08d76468503d109ab9ad56d636c2d8105d/sbt-scalapact-shared/src/main/scala/com/itv/scalapact/plugin/shared/Publisher.scala#L39

With this (`dXNlcm5hbWU6cGFzc3dvcmQ=` is "username:password" base64 encoded):
```
Map("Content-Type" -> "application/json", "Authorization" -> "Basic dXNlcm5hbWU6cGFzc3dvcmQ="),
```

The publish works and everything is fine.

Would you like me to create a pull-request adding basic auth header to requests to a broker?

### PR DESCRIPTION
**Pull request by jnatten**
Fixes #110 

There might be better ways to do this, but since i didn't get a reply on the issue i went ahead and did it this way :)

### CODE REVIEW

**Comment by davesmith00000** [comment]
I'm catching up. I was confused because I thought this had been done before, but the previous work - I think - just allowed for pact broker urls with basic auth in them for the purposes of fetching pact files, it didn't allow their use for publishing.

**Comment by jnatten** [comment]
I could only find support for having the credentials in the url, but as far as i could tell the http clients i tried didn't support basic authentication this way. 

So the result in my case was a 403, both for fetching and publishing. 

This PR adds the authorization header with `Basic` scheme ([MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Authentication#Authentication_schemes) / [RFC7617](https://tools.ietf.org/html/rfc7617#page-5))

**Comment by davesmith00000** [comment]
@jnatten This looks good. I have a personal aversion to tuples but it's a minor thing. Master has moved on since you raised this PR and there are a couple of merge conflicts - I think with your other work! If you'd like resolve them I'll merge this and we'll cut the next release ready for the new year!

**Comment by jnatten** [comment]
Sounds good, I rebased with master now :)

**Pull request merged**
