### PR TITLE
add module for http4s 0.21.0-M6

### PR DESCRIPTION
**Pull request by jbwheatley**

### CODE REVIEW

**Comment by davesmith00000** [comment]
Hi @jbwheatley, superficially looks fine - good idea testing the client.
Two comments:
1. As mentioned we tend not to pull in milestone versions because it causes problems for our users. Is this blocking anything? Can we afford to wait?
2. @dantb's build work is saying there are problems. Have you run `scripts/local-build-test.sh` having changed the dependencies to your new version and checked it's all ok?
Thanks,
Dave

**Comment by jbwheatley** [comment]
@davesmith00000 yeah it can wait. It wasn't pressing but we have a service being written using http4s 0.21 milestones, and it will need pact tests at some point.

**Comment by channingwalton** [comment]
looks like 0.21 will be released very soon

**Comment by channingwalton** [comment]
👍

**Pull request merged**
