### PR TITLE
Allow finalising a ScalaPactDescription within the forger DSL

### LINKED ISSUE #134: Allow finalising a ScalaPactDescription within the forger DSL
Within the DSL for the forger, you can currently only go all the way to running a consumer test. A `ScalaPactDescription` is finalised as part of the code to run the test:
```
def runConsumerTest ... =
  ScalaPactMock.runConsumerIntegrationTest(strict)(
    ScalaPactDescriptionFinal(
      consumer,
      provider,
      sslContextName,
      interactions.map(i => i.finalise),
      options
    )
  )(test)
```
Would it be reasonable to extract the construction of the `ScalaPactDescriptionFinal` to a separate finalise method? The use case I have is to share a pact definition between a test invoking `runConsumerTest` as normal, and programmatically setting up the stubber with multiple pacts for some other end-to-end tests.

### PR DESCRIPTION
**Pull request by razerno**
Closes #134

### CODE REVIEW

**Comment by razerno** [comment]
@davesmith00000, do you mind reviewing this PR? Thanks

**Comment by davesmith00000** [comment]
Hello! Sorry for being slow to respond to the issue. I can't say I fully understand it yet. Do you have example code where you programmatically set up the stubber with this new setup that I can look at?

**Comment by razerno** [comment]
No problem. So the pact stubber currently uses the following line to load any local pact files as a list of `Pact`s and combine them with a config.
https://github.com/ITV/scala-pact/blob/b45f5baed7e846d953d668bc9f9f156d8819e925/scalapact-standalone-stubber/src/main/scala/com/itv/standalonestubber/PactStubber.scala#L26
I've basically replicated some of the code that follows that to set up the stubber myself but manually providing it the list of pacts from the description created by the pact forger DSL.

So assuming I have a pact description:
```scala
val pactDescription = forgePact.between ...
```
I can then run consumer tests with it as normal...
```scala
pactDescription.runConsumerTest { mockConfig => ...
```
... as well as use the finalise method this PR extracts to start the stubber without requiring the pact to be written to file.
```scala
val pact = ScalaPactContractWriter.producePactFromDescription(pactDescription.finalise)
val configAndPacts = ConfigAndPacts(scalaPactSettings, List(pact))
val addInteractions = interactionManager.addToInteractionManager

val startStub: ScalaPactSettings => IPactStubber = pactStubber.start(interactionManager ...

(addInteractions andThen startStub)(configAndPacts)
```
This could then be used, for example, as a simulator for other integration tests where required when you haven't forged the pacts into files yet. My particular use case is an end-to-end integration test that runs in the same run as the cdc tests. Depending on the order the tests are executed then sometimes the tests forging the pacts haven't executed yet, and I wanted to avoid any dependencies between tests anyway. This also means the code stays as the source of truth rather than the temporary pact files created during runs (since they haven't yet been published to a broker either).

This could ideally be a refactor for the pact stubber itself as well in the future but that would be more involved so I left that out of the scope of this change. Hope that's all clear.

**Comment by razerno** [comment]
@davesmith00000, have you had a chance to look at this again?

**Pull request merged**
