### PR TITLE
Adds support for tagging pacts while publishing and verifying pacts with specified tags

### LINKED ISSUE #107: Is it possible to publish pacts to broker with tag(s)?
Here comes another question from me.
Couldn't find it in the documentation but i was wondering if is there was a way to publish pacts with tags?
I want to tag my published pacts with my branch name. (Also recommended by pact-foundation wiki: https://github.com/pact-foundation/pact_broker/wiki/Set-up-checklist#consumer-team)

Is there a way to do this with scala-pact or would i need to create some script?

### PR DESCRIPTION
**Pull request by jnatten**
Fixes #107 

This allows one to tag their published contracts and to verify contracts with specified tags.

As recommended by pact-foundation: https://github.com/pact-foundation/pact_broker/wiki/Using-tags#1-automatically-tag-with-branch-name-when-pact-is-published-recommended

### CODE REVIEW

**Comment by jnatten** [comment]
I don't really have any strong option either way.

I do agree that `pactBroker` might be a bit misleading, since most would probably want to use tags (Whether or not it is worth breaking the api for I have no idea).

**Comment by davesmith00000** [comment]
I don't think it needs to be a breaking change. I think we could leave the old one with a deprecation warning, and add another that was more descriptive.
Anyway, I shall try and merge this in tomorrow with another PR and see if I can get a release out.
Thanks again!

**Comment by jnatten** [comment]
@davesmith00000 
Sorry for nagging, but is there any ETA on this?
I've noticed that i forgot to add escaping of the tags (Say you want a tag with a `/` or a `#` symbol).
Do you want me to add it to this PR or make a separate one once this is merged?

**Comment by davesmith00000** [comment]
@jnatten I've merged it, time is not my friend at the moment! Delighted to get another PR with the escaping. :-)

**Comment by davesmith00000** [comment]
Also please don't apologise for nagging me a bit, I appreciate the work and I'm generally not quick enough merging it in! I need a nudge! :-)

**Pull request merged**
