### PR TITLE
Publish provider tests results to Pact broker

### LINKED ISSUE #71: How to pass verification result form provider to pact-broker?
Hi all,
I'm verifying the pact which is present in pact-broker from the provider using "SBT test". 
When I run the above command my pacts are getting verified but the verification result is not getting pushed to pact-broker. Can someone help me to resolve this issue(Do I need to add any extra parameters or am I missing any)?

### PR DESCRIPTION
**Pull request by garraspin**
Fixes #71

### CODE REVIEW

**Comment by garraspin** [comment]
I still need to add tests. But I wanted to initiate the conversation already. Manual tests look good

**Comment by davesmith00000** [comment]
Hello! Really excited that you've had a go at this.
I noticed you're still pushing to this PR - is it ready for review?
Would you like to talk me through it a bit or give me a starting point? Otherwise I'll just try and wade through it. :-)

**Comment by garraspin** [comment]
Hi! 
Please proceed with the review. The functionality works and  I would like to know your opinion. Basically I changed the provider tests so if the Pact contains `_links` attribute in the json it would keep those to retrieve the link where the results can be published to the pact broker. The `pactBroker` case class has a new Option[BrokerPublishData] parameter that if defined will be used to publish the results. 
Let me know how to contact you if you want more explanations.

**Comment by garraspin** [comment]
Hi @davesmith00000 , Were you able to have a look at the PR? Can you merge?

**Comment by davesmith00000** [comment]
Hi, Sorry about the delay. Looks like it does the right thing. How are you testing it can I ask?

**Comment by garraspin** [comment]
I just added some unit tests for ResultPublisher. I am open to suggestions on how to tests the interaction with the broker on a integration test, if needed.

**Comment by davesmith00000** [comment]
@garraspin You have not been forgotten, just hectic, I'm going to try and get this merged over the weekend.

**Comment by davesmith00000** [comment]
Merged. I'm going to do some further verification before it goes into a release.

**Comment by garraspin** [comment]
Nice! Thanks for looking into it

**Comment by davesmith00000** [comment]
Update: We've experienced a slight wrinkle in that one of the classes doesn't appear to be exposed to the *sbt files, but we're fixing it.

**Comment by davesmith00000** [comment]
This is the specific error:
```
error: not found: value BrokerPublishData
      scalaPactEnv := ScalaPactEnv(Some("http"), Some("http://pactbroker.infradev.oasvc.itv.com/"), None, None, None, None, None, Option(BrokerPublishData("0.0.1", None)))
                                                                                                                                         ^
[error] sbt.compiler.EvalException: Type error in expression
[error] sbt.compiler.EvalException: Type error in expression
```
Looking at this now.

**Comment by davesmith00000** [comment]
Right, fixed!
You can now use `BrokerPublishData ` in `build.sbt`. I realised too late that you'd added a nice helper method so that you didn't need that at all. Oh well.
I've also verified that this works! I've published results from an external and internal verification.
Need to update the docs now.

**Comment by garraspin** [comment]
Great that you fixed it! Thanks

**Comment by davesmith00000** [comment]
It's not quite showing up on maven.org yet but you should be able to resolve version `2.3.3` now and try it. Thanks again for the work!

**Pull request merged**
